//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeDetectionClass.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrimeUser
    {
        public int UserId { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string ContactNo { get; set; }
        public string District { get; set; }
        public int IsPolice { get; set; }
    }
}
