//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeDetectionClass.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrimeComment
    {
        public int CommentId { get; set; }
        public Nullable<int> CrimeId { get; set; }
        public string CommentDesc { get; set; }
    }
}
