//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeDetectionClass.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCrime
    {
        public int CrimeId { get; set; }
        public string Crime { get; set; }
        public string Description { get; set; }
        public string Criminal { get; set; }
        public string Location { get; set; }
        public int IsWomensCrime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
    }
}
